# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='index',
        ),
    ]
