# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161114_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='blog.Tag', verbose_name='标签'),
        ),
    ]
