# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161114_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='article',
            order_with_respect_to='date_publish',
        ),
    ]
