# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161114_1455'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='article',
            order_with_respect_to=None,
        ),
    ]
