# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161114_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
