# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161114_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_publish'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
